import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		boolean girl;
		boolean boy;
		int children;
		double child;
		int twoCount= 0;
		int threeCount=0;
		int fourCount=0;
		double avarege = 0;




		for (int i = 0; i < T; i++) {
			girl=false;
			boy=false;
			children=0;
			do{
				child= (generator.nextDouble());
				if(child>0.5) {
					boy= true;
					// System.out.print("b ");
				}
				else {
					girl= true;
					// System.out.print("g ");
				}
				children= children+1;
				
			} 
			while(girl!=true || boy!=true);

			avarege += (double) children;

			if (children==2) {
				twoCount++;
			}
			else if(children==3) {
				threeCount++;
			}
			else{
				fourCount++;
			}
		}
		avarege /= (double) T;

		String mode = "";
		int max = 0;

		max = Math.max(twoCount, threeCount);
		max = Math.max(max, fourCount);

		if (max == twoCount) {
			mode = "2.";
		}
		else if (max == threeCount) {
			mode = "3.";
		}
		else {
			mode = "4 or more.";
		}

		System.out.println("Average: " + avarege + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + twoCount);
		System.out.println("Number of families with 3 children: " + threeCount);
		System.out.println("Number of families with 4 or more children: " + fourCount);
		System.out.println("The most common number of children is " + mode);
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
